// Localized strings for the chat webview chrome.
import { formatCount } from "../../common/utils";
import type { UiLanguage } from "../../common/i18n";
import { formatCountLabel } from "./helpers";
import { state } from "./state";

export type TextKey =
  | "messages" | "context" | "debug" | "companion" | "emptyConversation" | "typeMessage"
  | "agentsHint" | "modelsHint" | "shellHint" | "commandsHint" | "filesHint" | "send" | "interrupt" | "queued" | "queueMessage" | "continue"
  | "new" | "sessions" | "agents" | "models" | "logs" | "notifications" | "sessionJson" | "sidebar" | "themes" | "quit" | "refresh" | "close"
  | "reconnecting" | "thinking" | "openingModels" | "openingModelPicker" | "openingAgents" | "openingSessions"
  | "openingLogs" | "openingTools" | "openingFiles" | "openingShell" | "openingDiagnostics" | "openingDoctor"
  | "openingSupportBundle" | "openingSessionJson" | "openingDiff" | "openingRollback" | "openingWorkspace"
  | "openingManagement" | "openingSettings" | "openingApproval" | "openingTheme" | "runningCommand"
  | "unknownCommand" | "typeHelp"
  | "profile" | "session" | "approvalMode" | "noEvents" | "notificationsTitle" | "notificationsSubtitle" | "noEventsBody"
  | "copySessionId" | "changeWorkspace"
  | "agentQuestion" | "submit" | "cancel"
  | "commandHelpTitle" | "commandHelpSubtitle" | "noHelpEntry" | "copyFailed" | "copied" | "nothingToCopy"
  | "sessionCopied"
  | "toolsMeta" | "filesMeta" | "preparingImages" | "imageTooLarge" | "imageAttached" | "imageWhileRunning"
  | "imagePreparingMeta" | "imageReadingMeta" | "imageCompressingMeta"
  | "imageCompressed" | "removeImage"
  | "imageUnsupported" | "imageUnsupportedTitle" | "imageUnsupportedBody"
  | "pasteTruncated" | "imagePathMentioned"
  | "toolNotFound" | "noToolOutput" | "modelDialogSubtitle" | "agentDialogSubtitle"
  | "eventStream" | "copySnapshot" | "copySupportBundle" | "debugSnapshotCopied"
  | "showSidebar" | "hideSidebar" | "closeSidebar" | "refreshSessions" | "noSavedSessions"
  | "resumeSession" | "deleteSession" | "currentSession" | "loadingSessions" | "plan" | "capabilities"
  | "ready" | "loadingAgent" | "processing" | "welcomeEyebrow" | "welcomeTitle" | "welcomeSubtitle"
  | "workingDirectory" | "startingPlaceholder";

export const TEXT: Record<UiLanguage, Record<TextKey, string>> = {
  en: {
    messages: "Messages",
    context: "Context",
    debug: "Debug",
    companion: "Buddy",
    emptyConversation: "Your conversation will appear here",
    typeMessage: "Type a message",
    agentsHint: "# Agents",
    modelsHint: "$ Models",
    shellHint: "! Shell",
    commandsHint: "/ Commands",
    filesHint: "@ Files",
    send: "Send",
    interrupt: "Interrupt",
    queued: "Queued",
    queueMessage: "Queue",
    continue: "Continue",
    new: "New",
    sessions: "Sessions",
    agents: "Agents",
    models: "Models",
    logs: "Logs",
    notifications: "Notifications",
    sessionJson: "Session JSON",
    sidebar: "Sidebar",
    themes: "Themes",
    quit: "Quit",
    refresh: "Refresh",
    close: "Close",
    reconnecting: "Reconnecting...",
    thinking: "thinking",
    openingModels: "Opening Models...",
    openingModelPicker: "Opening model picker...",
    openingAgents: "Opening Agents...",
    openingSessions: "Opening Sessions...",
    openingLogs: "Opening Logs...",
    openingTools: "Opening Tools...",
    openingFiles: "Opening Files...",
    openingShell: "Opening workspace terminal...",
    openingDiagnostics: "Opening diagnostics...",
    openingDoctor: "Opening health check...",
    openingSupportBundle: "Copying support bundle...",
    openingSessionJson: "Opening Session JSON...",
    openingDiff: "Opening session diff...",
    openingRollback: "Opening rollback...",
    openingWorkspace: "Opening workspace picker...",
    openingManagement: "Opening iCode management...",
    openingSettings: "Reloading settings...",
    openingApproval: "Opening approval mode...",
    openingTheme: "Opening themes...",
    runningCommand: "Running command...",
    unknownCommand: "Unknown command",
    typeHelp: "Type /help.",
    profile: "Profile",
    session: "Session",
    approvalMode: "Approval mode",
    copySessionId: "Copy session id",
    changeWorkspace: "Change workspace",
    agentQuestion: "Agent Question",
    submit: "Submit",
    cancel: "Cancel",
    noEvents: "No events yet",
    notificationsTitle: "Notifications",
    notificationsSubtitle: "Session event log",
    noEventsBody: "No events recorded yet. iCode debug events will appear here as they happen.",
    commandHelpTitle: "iCode Commands",
    commandHelpSubtitle: "Search commands by typing after /",
    noHelpEntry: "No help entry for",
    copyFailed: "Copy failed.",
    copied: "Copied.",
    nothingToCopy: "Nothing to copy.",
    sessionCopied: "Session id copied.",
    toolsMeta: "tool",
    filesMeta: "file",
    preparingImages: "Preparing image...",
    imageTooLarge: "Image is too large to attach.",
    imageAttached: "Image attached.",
    imageWhileRunning: "Send images after the current turn finishes.",
    imagePreparingMeta: "Preparing...",
    imageReadingMeta: "Reading...",
    imageCompressingMeta: "Compressing...",
    imageCompressed: "compressed",
    removeImage: "Remove image",
    imageUnsupported: "The active model profile does not support image input.",
    imageUnsupportedTitle: "Image Input Not Available",
    imageUnsupportedBody: "The active iCode model profile does not advertise vision/image input. Switch to a vision-capable model profile, then paste or drop the image again.",
    pasteTruncated: "Paste truncated",
    imagePathMentioned: "Image path mentioned.",
    toolNotFound: "Tool not found.",
    noToolOutput: "(no output)",
    modelDialogSubtitle: "Configure model connections, credentials, and capabilities.",
    agentDialogSubtitle: "Manage iCode agent profiles.",
    eventStream: "Event Stream",
    copySnapshot: "Copy Snapshot",
    copySupportBundle: "Copy Support Bundle",
    debugSnapshotCopied: "Debug snapshot copied.",
    showSidebar: "Show auxiliary panel",
    hideSidebar: "Hide auxiliary panel",
    closeSidebar: "Close auxiliary panel",
    refreshSessions: "Refresh sessions",
    noSavedSessions: "No saved sessions in this workspace yet.",
    resumeSession: "Resume session",
    deleteSession: "Delete session",
    currentSession: "Current",
    loadingSessions: "Loading sessions…",
    plan: "Plan",
    capabilities: "Capabilities",
    ready: "Ready",
    loadingAgent: "Loading agent",
    processing: "Working",
    welcomeEyebrow: "AI coding agent for VS Code",
    welcomeTitle: "What are you building?",
    welcomeSubtitle: "Describe a task, ask about the codebase, or reference a file to get started.",
    workingDirectory: "Working directory",
    startingPlaceholder: "iCode is starting…",
  },
  "zh-CN": {
    messages: "消息",
    context: "上下文",
    debug: "调试",
    companion: "Buddy",
    emptyConversation: "你的对话会显示在这里",
    typeMessage: "输入消息",
    agentsHint: "# 智能体",
    modelsHint: "$ 模型",
    shellHint: "! 终端",
    commandsHint: "/ 命令",
    filesHint: "@ 文件",
    send: "发送",
    interrupt: "中断",
    queued: "已排队",
    queueMessage: "加入队列",
    continue: "继续",
    new: "新建",
    sessions: "会话",
    agents: "智能体",
    models: "模型",
    logs: "日志",
    notifications: "通知",
    sessionJson: "会话 JSON",
    sidebar: "侧栏",
    themes: "主题",
    quit: "退出",
    refresh: "刷新",
    close: "关闭",
    reconnecting: "正在重连...",
    thinking: "思考中",
    openingModels: "正在打开模型...",
    openingModelPicker: "正在打开模型选择器...",
    openingAgents: "正在打开智能体...",
    openingSessions: "正在打开会话...",
    openingLogs: "正在打开日志...",
    openingTools: "正在打开工具...",
    openingFiles: "正在打开文件...",
    openingShell: "正在打开工作区终端...",
    openingDiagnostics: "正在打开诊断报告...",
    openingDoctor: "正在打开健康检查...",
    openingSupportBundle: "正在复制支持快照...",
    openingSessionJson: "正在打开会话 JSON...",
    openingDiff: "正在打开会话差异...",
    openingRollback: "正在打开回滚...",
    openingWorkspace: "正在打开工作区选择器...",
    openingManagement: "正在打开 iCode 管理...",
    openingSettings: "正在重载设置...",
    openingApproval: "正在打开审批模式...",
    openingTheme: "正在打开主题...",
    runningCommand: "正在运行命令...",
    unknownCommand: "未知命令",
    typeHelp: "输入 /help 查看帮助。",
    profile: "配置",
    session: "会话",
    approvalMode: "审批模式",
    copySessionId: "复制会话 ID",
    changeWorkspace: "切换工作区",
    agentQuestion: "智能体提问",
    submit: "提交",
    cancel: "取消",
    noEvents: "暂无事件",
    notificationsTitle: "通知",
    notificationsSubtitle: "会话事件日志",
    noEventsBody: "暂无事件。iCode 前端调试事件会在这里出现。",
    commandHelpTitle: "iCode 命令",
    commandHelpSubtitle: "输入 / 后继续键入即可搜索命令",
    noHelpEntry: "没有帮助条目：",
    copyFailed: "复制失败。",
    copied: "已复制。",
    nothingToCopy: "没有可复制内容。",
    sessionCopied: "会话 ID 已复制。",
    toolsMeta: "个工具",
    filesMeta: "个文件",
    preparingImages: "正在处理图片...",
    imageTooLarge: "图片过大，无法附加。",
    imageAttached: "图片已附加。",
    imageWhileRunning: "请等当前轮次结束后再发送图片。",
    imagePreparingMeta: "处理中...",
    imageReadingMeta: "读取中...",
    imageCompressingMeta: "压缩中...",
    imageCompressed: "已压缩",
    removeImage: "移除图片",
    imageUnsupported: "当前模型配置不支持图片输入。",
    imageUnsupportedTitle: "图片输入不可用",
    imageUnsupportedBody: "当前 iCode 模型配置没有声明 vision/image input 能力。请切换到支持视觉的模型配置后，再重新粘贴或拖入图片。",
    pasteTruncated: "粘贴内容已截断",
    imagePathMentioned: "图片路径已转为引用。",
    toolNotFound: "未找到工具。",
    noToolOutput: "（无输出）",
    modelDialogSubtitle: "配置模型连接、凭据与能力。",
    agentDialogSubtitle: "管理 iCode 智能体配置。",
    eventStream: "事件流",
    copySnapshot: "复制快照",
    copySupportBundle: "复制支持快照",
    debugSnapshotCopied: "调试快照已复制。",
    showSidebar: "打开辅助看板",
    hideSidebar: "收起辅助看板",
    closeSidebar: "关闭辅助看板",
    refreshSessions: "刷新会话",
    noSavedSessions: "此工作区还没有已保存会话。",
    resumeSession: "恢复会话",
    deleteSession: "删除会话",
    currentSession: "当前",
    loadingSessions: "正在加载会话…",
    plan: "计划",
    capabilities: "能力",
    ready: "已就绪",
    loadingAgent: "正在加载智能体",
    processing: "处理中",
    welcomeEyebrow: "VS Code 中的 AI 编程智能体",
    welcomeTitle: "今天要构建什么？",
    welcomeSubtitle: "描述开发任务、询问代码库，或引用文件即可开始。",
    workingDirectory: "工作目录",
    startingPlaceholder: "iCode 正在启动…",
  },
};

export const SLASH_ZH: Record<string, { title: string; description: string }> = {
  new: { title: "新建会话", description: "启动一个新的 iCode 会话" },
  exit: { title: "关闭聊天", description: "关闭 iCode Chat 面板" },
  resume: { title: "恢复", description: "恢复最近的会话" },
  sessions: { title: "会话", description: "浏览并加载已保存会话" },
  agents: { title: "智能体", description: "管理智能体配置" },
  switch: { title: "切换智能体", description: "切换当前智能体" },
  profiles: { title: "智能体配置", description: "查看智能体配置详情" },
  model: { title: "模型", description: "切换当前模型配置" },
  models: { title: "模型管理", description: "管理模型配置" },
  modelnew: { title: "新建模型", description: "创建新的模型配置" },
  modeldelete: { title: "删除模型", description: "删除模型配置" },
  agentdelete: { title: "删除智能体", description: "删除智能体配置" },
  runtime: { title: "运行时", description: "查看 ACP 运行时详情" },
  tools: { title: "工具", description: "查看已加载工具" },
  files: { title: "文件", description: "查看已加载工作区文件" },
  search: { title: "搜索工作区", description: "在 VS Code 搜索视图中搜索当前工作区" },
  grep: { title: "检索工作区", description: "在 Quick Pick 中列出匹配行" },
  find: { title: "查找文件", description: "按文件名打开工作区文件" },
  mention: { title: "引用文件", description: "在输入框插入文件引用" },
  attach: { title: "附加文件", description: "把工作区文件内容附加到输入框" },
  roots: { title: "目录范围", description: "显式选择额外工作目录" },
  selection: { title: "附加选区", description: "附加编辑器选区与行号" },
  problems: { title: "附加问题", description: "附加编辑器诊断信息" },
  cd: { title: "工作区", description: "切换当前会话工作区目录" },
  logs: { title: "日志", description: "查看 VSIX 和 ACP 前端日志" },
  debug: { title: "调试事件", description: "查看最近前端事件通知" },
  debugcopy: { title: "调试快照", description: "复制 VSIX 前端状态和最近事件" },
  history: { title: "会话 JSON", description: "查看结构化会话历史" },
  shell: { title: "终端", description: "打开工作区终端，或运行 /shell <命令>" },
  diff: { title: "差异", description: "查看会话中的文件改动" },
  rollback: { title: "回滚", description: "按最近轮数或保留轮次预览并确认回滚" },
  approval: { title: "审批", description: "设置工具审批模式" },
  reload: { title: "重载设置", description: "重载 iCode 设置" },
  mcptest: { title: "测试 MCP", description: "测试 HTTP MCP 服务器" },
  manage: { title: "管理", description: "打开 iCode 管理面板" },
  theme: { title: "主题", description: "选择与 TUI 对齐的主题" },
  diagnostics: { title: "诊断报告", description: "打开 VSIX/ACP 诊断报告" },
  support: { title: "支持快照", description: "复制可分享的 VSIX/TUI 排查快照" },
  trajectory: { title: "用量与执行轨迹", description: "查看历史用量、耗时和时间线，或导出分析" },
  workflow: { title: "工作流", description: "选择并运行 CLI 工作流，查看结果或取消运行" },
  doctor: { title: "健康检查", description: "检查 VSIX/ACP 状态并提供修复入口" },
  notifications: { title: "通知", description: "查看最近前端通知" },
  clear: { title: "清空显示", description: "仅清空显示，保留会话上下文；新上下文请用 /new" },
  rename: { title: "会话本地名称", description: "设置此 VS Code 工作区的会话名称，不修改 TUI 标题" },
  prompts: { title: "历史输入", description: "搜索并填回历史提示词，不自动发送（Ctrl+R）" },
  copy: { title: "复制", description: "复制对话轮次" },
  fold: { title: "折叠", description: "折叠/展开工具详情和回复" },
  help: { title: "帮助", description: "显示命令帮助" },
  subretry: { title: "重试子智能体", description: "重试最近的子智能体" },
  subabort: { title: "终止子智能体", description: "终止正在运行的子智能体" },
  companion: { title: "Companion", description: "查看伙伴状态" },
};

export function t(key: TextKey): string {
  return TEXT[state.uiLanguage][key];
}

export function countLabel(count: number, zhKey: "toolsMeta" | "filesMeta", enNoun: string): string {
  return state.uiLanguage === "zh-CN" ? `${formatCount(count)}${t(zhKey)}` : formatCountLabel(count, enNoun);
}
